### ISSUE TITLE
[Refactor]  Meta Server refector

### ISSUE THREAD

**Issue by roseboy-liu** [cnosdb/cnosdb#1146]
**Is your feature request related to a problem? Please describe.**
- [x] Modify the http library to remove the reference to actix-web and use the grpc specification for communication between the client and server to standardize the API interface between them.
- [x] Due to the serious problem of disk space expansion in sled and the project being in an unmaintained state, switch to rocksdb.
- [x] Modify the code logic of where "unwrap" is used.
- [x] Use grpc for communication in raft.
- [x] remove meta client module from meta server.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zipper-meng** [comment]
### Features request

- Add default config so that we can let the config file omitted.
- Add a sub-command `config` to print the default config.
- The `/debug` api returns the pure json format, not the yaml + json format.
