### ISSUE TITLE
[Feature] Support replica placement policy

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1669]
- [x] Syntax supports creating and show storage policies and specifying storage policies when creating a database.

  simple model, all replicas are placed on rack1 in dc1.
  `create placement_policy policy_name WITH rule simple dc 'dc1' rack 'rack1';`
  
  perceptual rack mode, all replicas are placed on different racks (rack1-4) in dc1
  `create placement_policy policy_name WITH rule rack_aware dc 'dc1' rack 'rack1,rack2,rack3,rack4';`
  
  perceptual dc mode, all replicas are placed in different availability zones (dc1-4) as much as possible.
  `create placement_policy policy_name WITH rule dc_aware dc 'dc1,dc2,dc3,dc4';`
   
  check placement_policys.
 `select * from information_schema.placement_policys;`

   specifying storage policies and alter storage policies
  `CREATE DATABASE my_db WITH TTl '3560d' SHARD 1 VNOdE_DURATiON '5m' REPLICA 2 pRECISIOn 'ms' placement_policy policy_name;`
   `alter database db1 with placement_policy p2;`

- [x] The configuration supports assigning dc and rack to nodes, which can be displayed using the `show datanodes` command.
   [node_basic]
   location = "/dc1/rack1"
- [x] When writing data, it supports selecting nodes based on the storage policy specified by the database and the dc and rack of the nodes.
- [x] add drop placement_policy feature, and when placement_policy association with db, forbid drop placement_policy
   `drop placement_policy p1;`
- [x] add alter placement_policy feature, and when placement_policy association with db, forbid alter placement_policy
   `alter placement_policy p1 with rule simpl dc 'dc1' rack 'rack1';`
- [x] Regarding the impact of data migration, such as: node offline,tiered storage, node migration, etc.

**Comment by roseboy-liu** [comment]
We have already provided this feature in the enterprise version.

**Comment by Benxiaohai001** [comment]
https://github.com/cnosdb/cnosdb-enterprise/pull/139
