### ISSUE TITLE
Planning to upgrade datafusion version

### ISSUE THREAD

**Issue by yukkit** [cnosdb/cnosdb#786]
**Is your feature request related to a problem? Please describe.**

planning to upgrade the datafusion version at some point in the future, and the bugs of datafusion in the current version can be related to this issue

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
The upgrade will close the following issues
- [ ] #784 
- [x] #830 datafusion fixed in 15.0.0
- [ ] datafusion panic "At least two values are needed to calculate variance" fixed in 16.0.0 https://github.com/apache/arrow-datafusion/issues/4843
- [ ] #877 support `Date` to `Timestamp`
